spring:
  application:
    name: delta-sharing-onprem
  
  # Database Configuration (H2 for development)
  datasource:
    url: jdbc:h2:mem:deltasharing
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  
  # SQL initialization
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Thymeleaf Configuration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  
  # DevTools
  devtools:
    restart:
      enabled: true

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Delta Sharing Configuration
delta:
  sharing:
    auth:
      enabled: true
      # Configure your bearer token here (leave empty for development mode)
      bearer-token: ${DELTA_SHARING_TOKEN:}

# Logging
logging:
  level:
    com.databricks.deltasharing: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
    org.springframework.security: INFO
